# Generated by Django 5.0.7 on 2024-07-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
        ),
    ]
